### ISSUE TITLE
The WernerChecker.cfg file is missing from the repo

### ISSUE THREAD

**Issue by linuxgurugamer** [Magion/WernherChecker#6]
I wanted to create a pull for you with my updated cfg file which has the additional checklists, but the file is missing from the repo, I checked the dev as well as the main branch.
Also, all of the icons are missing from the repo as well.
Would be helpful to have them all here, both as a backup for yourself and to make it easier to fork it, if someone wanted to.  also, for someone like myself, if I just want ot make a fix for you, if the whole thing isn't in the repo, that makes it hard to build a local package

**Comment by Magion** [comment]
I already added them in PR #5. They are right [here](https://github.com/Magion/WernherChecker/tree/dev/Data).

**Comment by linuxgurugamer** [comment]
Duh!  I always forget to look dev.

I'll be pushing an update for it this evening, with 3 other checklists included
